# -*- coding: utf-8 -*-
"""Atividade logica de programacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFbziaHL5n1DL_SLv2iEioHEnfYF-YCx
"""

#Varialve auxiliar.
executar = 1

# Executa os codigos em cada disciplina.
while executar == 1:

  # Informa qual disciplina.
  disciplina = input("Qual é a disciplina:")

  # Varaivel de controle da quantidades de alunos.
  time = int(input("Numero de alunos:"))

  # Lista de alunos.
  alunos = []

  # Execução do laço de repetição.
  for aluno in range(time):

    # Ordem do aluno e qual a sua disciplina
    print("Preencha as informações do aluno numero", (aluno+1), "da disciplina", disciplina)

    # Coleta dos dados dos alunos.
    nome = input("Nome do aluno: ")
    n1 = float(input("Nota do primeiro bimestre: "))
    n2 = float(input("Nota do segundo bimestre: "))
    n3 = float(input("Nota do terceiro bimestre: "))
    n4 = float(input("Nota do quarto bimestre: "))
    faltas = int(input("Percentual de faltas do aluno: "))

    # Contagem das notas.
    media = (n1 + n2 + n3 + n4) / 4

    #Vefifica a situação do aluno.
    if (media >= 5 and faltas <= 75):
      resultado = "APROVADO"
    else:
      resultado = "REPROVADO"

    # Armazena as informações em lista.
    alunos.append([nome, n1, n2, n3, n4, media, faltas, resultado])

  # Nome da disciplina.
  print("Informações da disciplina de", disciplina)

  # Exibe as informações da lista, linha linha.
  for linha in alunos:
    print("Nome do aluno: ", linha[0])
    print("Nota do primeiro bimestre:", linha[1])
    print("Nota do segundo bimestre:", linha[2])
    print("Nota do terceiro bimestre:", linha[3])
    print("Nota do quarto bimestre:", linha[4])
    print("Media das notas:", linha[5])
    print("Percentual de faltas:", linha[6], "%")
    print("Situação:", linha[7])

  # Verifica se terá novas entradas de informações
  print("Deseja cadastrar novas informações para outra disciplina")
  executar = int(input("Digite 0 para NÃO e 1 para SIM:"))